### ISSUE TITLE
Periodic error when running against Aurora Serverless create-report or create-compare-report 

### ISSUE THREAD

**Issue by alecl** [awslabs/pireporter#9]
I believe this is happening due to this call that passes an undefined snapshotRange which we don't have when creating a report

// Gather general information
`getGeneralInformation({DBInstanceIdentifier: InstanceName}, options, snapshotRange)`

which for serverless eventually makes this call with a missing .endTime

```
    if (DBInstanceClass === 'db.serverless') {
       try {
         var {minACUs, maxACUs}  = await getServerlessMaxACU(pi, DbiResourceId, snapshotRange.endTime)
       } catch (err) { reject(err) }
    }
```

Suggest wrapping the call to not happen for report creation something similar to this

```
if (!(options["create-report"]) && !(options["create-compare-report"])) {
...
}
```

```
helpers.js:693
  const startTimeSpecial = new Date(endTime.getTime() - 15 * 60 * 1000);
                                           ^

TypeError: Cannot read properties of undefined (reading 'getTime')
    at /Users/gitproj/pireporter/helpers.js:693:45
    at new Promise (<anonymous>)
    at getServerlessMaxACU (/Users/gitproj/pireporter/helpers.js:691:10)
    at /Users/gitproj/pireporter/helpers.js:775:42
    at /Users/gitproj/pireporter/node_modules/@smithy/smithy-client/dist-cjs/index.js:113:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by aychin-aws** [comment]
Hmm, thank you for analyzes. We should not call `getGeneralInformation()` when creating reports, we have all information required in snapshot file.

You get this error not every execution, it is interesting in which cases you get it? Does it depend on snapshot file?
